apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: manish198646/first-app:5
          imagePullPolicy: Always
          env:
            - name: MONGODB_HOST
              value: "172.16.15.7"
          volumeMounts:
            - mountPath: /app/public
              name: story-volume
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: story-volume
          persistentVolumeClaim:
            claimName: host-pvc
